# Generated by Django 2.1.7 on 2019-03-01 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='charity_name',
            new_name='charity_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
