# Generated by Django 2.1.7 on 2019-03-22 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(default='deargoodpeople', max_length=100)),
                ('hours', models.FloatField(default=0)),
                ('date', models.CharField(default='2019-03-22', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteers',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='charity_name',
            new_name='charity_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
