# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number_hours', models.FloatField()),
                ('charity_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
